; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_n16r8]
platform = espressif32
; 這裡用最通用的 S3 開發板作為基底
board = esp32-s3-devkitc-1
framework = arduino

; 設定序列埠監控視窗的速度 (跟你在 Arduino IDE 右下角選的一樣)
monitor_speed = 115200

lib_deps =
    zinggjm/GxEPD2
    adafruit/Adafruit GFX Library

; ==================================
; 🚀 強制解鎖 N16R8 的硬體封印設定
; ==================================

; 1. 指定 16MB 的 Flash 容量 (預設通常只有 4MB 或 8MB)
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; 2. 喚醒 8MB OPI PSRAM (解決相機破圖、當機的關鍵)
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue